### PR TITLE
[VET-4697] remove unused fields

### PR DESCRIPTION
**Pull request by anneeb**
VET-4697

### CODE REVIEW

**Comment by anneeb** [comment]
@paulplace when you have a chance, can you let me know if this contract looks ok for your Portal work? or at least if there's anything included/not included that raises concern on your end.

**Review by paulplace — APPROVED** [review]
LGTM

**Comment by paulplace** [comment]
@anneeb is this still a change you want to commit, or has its time passed?

**Comment by paulplace** [comment]
There's no rush. I just wanted to make sure this PR is still relevant.

**Review by mysticfalconvt — APPROVED** [review]

**Pull request merged**
