### PR TITLE
[VET-2602] Update helper in portal-sdk to give productPath

### PR DESCRIPTION
**Pull request by SpiralP**
VET-2602 (VET-<span></span>2326)

* let slash after connection index be optional (ie `/u/0/explorer`)
* add `productPath` to getCurrentConnectionInfo

---

related to:
* https://github.com/stardog-union/cloud-login/pull/426
* https://github.com/stardog-union/lassie/pull/355

### CODE REVIEW

**Comment by paulambro** [comment]
@joshhk72 , @jhartling reminder on this PR needing review

**Review by joshhk72 — APPROVED** [review]
Weird I didn't get a notification/email till Paul's mention. LGTM!

**Review by jhartling — APPROVED** [review]
LGTM!

**Comment by paulambro** [comment]
@SpiralP can we merge this now?

**Pull request merged**
